# tasks file for apache2
- name: install httpd
  yum:
    name: httpd
    state: latest

- name: ensure httpd is enabled
  service:
    name: httpd
    enabled: yes
    state: started

- name: Create a directory if it does not exist
  file:
    path: /opt/html
    state: directory
    owner: apache
    group: apache
    mode: 0755

- name: Update DocumentRoot in httpd.conf
  replace:
    path: /etc/httpd/conf/httpd.conf
    regexp: 'DocumentRoot "/var/www/html"'
    replace: 'DocumentRoot "/opt/html"'
  notify: restart httpd

- name: Update <Directory "/var/www"> in httpd.conf
  replace:
    path: /etc/httpd/conf/httpd.conf
    regexp: '<Directory "/var/www">'
    replace: '<Directory "/opt/html">'
  notify: restart httpd

- name: Update <Directory "/var/www/html"> in httpd.conf
  replace:
    path: /etc/httpd/conf/httpd.conf
    regexp: '<Directory "/var/www/html">'
    replace: '<Directory "/opt/html">'
  notify: restart httpd

- name: add vhost config
  template:
    src: vhost.j2
    dest: /etc/httpd/conf.d/{{ ansible_hostname }}.conf
  notify: restart httpd

- name: copy index
  template:
    src: index.j2
    dest: /opt/html/index.html
    owner: apache
    group: apache
    mode: 0644
  notify: restart httpd

