# tasks file for apache2
- name: install httpd
  apt:
    name: apache2
    state: latest

- name: ensure apache2 is enabled
  service:
    name: apache2
    enabled: yes
    state: started

- name: copy index
  template:
    src: index.j2
    dest: /var/www/html/index.html
    owner: www-data
    group: www-data
    mode: 0644
  notify: restart apache2

- name: enable nginx on ufw
  ufw:
    state: enabled
    rule: allow
    port: "{{ item }}"
    proto: tcp
  loop:
  - http
  - https
