# tasks file for haproxy
- name: install haproxy
  yum:
    name: haproxy
    state: latest

- name: ensure haproxy is enabled and started
  service:
    name: haproxy
    enabled: yes
    state: "started"

- name: copy cfg
  template:
    src: haproxy.j2
    dest: /etc/haproxy/haproxy.cfg
  notify: restart haproxy
